pipeline {
    agent any
	options {
		// Keep the 10 most recent builds
		buildDiscarder(logRotator(numToKeepStr:'10'))
	}
	tools {
		// Install the Maven version configured as "M3" and add it to the path.
		maven "M3"
	}
    stages {
		stage('Git Checkout') {
			steps {
				checkout([
					$class: 'GitSCM',
					branches: [[name: '*/master']],
					extensions: [
					],
					userRemoteConfigs: [
						[
						    //https git clone
                            //url: 'https://github.com/ivanlevsky/stand-alone-complex-tomato.git'

                            //ssh git clone
                            credentialsId: 'jenkins-ssh-key',
                            url: 'git@github.com:ivanlevsky/stand-alone-complex-tomato.git'
						]
					]
				])
			}
		}

        stage('Build Project') {
            steps {
                sh 'cp ./test\\ file/cicd/pom.xml  ./'
				sh 'mvn -B -DskipTests clean package'
            }
        }

		stage('Test') {
			steps {
				sh 'mvn test'
			}
			post {
				always {
					junit 'target/surefire-reports/*.xml'
				}
				success {
					echo 'I succeeded!'
					mail to: 'zhou_zhiqi@hoperun.com',
							subject: "Success Pipeline: ${currentBuild.fullDisplayName}",
							body: "Something is wrong with ${env.BUILD_URL}"
				}
				unstable {
					echo 'I am unstable :/'
				}

				failure {
					echo 'I failed :('
				}

				changed {
					echo 'Things were different before...'
				}
			}

		}

    }
}