pipeline {
    agent any
	tools {
		// Install the Maven version configured as "M3" and add it to the path.
		maven "M3"
	}
    stages {
		stage('git checkout') {
			steps {
				checkout([
					$class: 'GitSCM',
					branches: [[name: '*/master']],
					extensions: [
					],
					userRemoteConfigs: [
						[
						    //https git clone
                            //url: 'https://github.com/ivanlevsky/stand-alone-complex-tomato.git'

                            //ssh git clone
                            credentialsId: 'jenkins-ssh-key',
                            url: 'git@github.com:ivanlevsky/stand-alone-complex-tomato.git'
						]
					]
				])
			}
		}

        stage('build project') {
            steps {
				sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}